CREATE TABLE stats(
	id SERIAL PRIMARY KEY,
	chrctr INTEGER REFERENCES characters(id),
	str INTEGER NOT NULL,
	con INTEGER NOT NULL,
	dex INTEGER NOT NULL,
	wis INTEGER NOT NULL,
	intl INTEGER NOT NULL,
	cha INTEGER NOT NULL
)

CREATE TABLE info(
	id SERIAL PRIMARY KEY,
	chrctr INTEGER REFERENCES characters(id),
	hp INTEGER NOT NULL,
	ac INTEGER NOT NULL,
	bab INTEGER NOT NULL,
	ref INTEGER NOT NULL,
	fort INTEGER NOT NULL,
	con INTEGER NOT NULL,
	descrip TEXT
)